defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-mysql2_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock


development:
  <<: *defaults
  database: allaroundme_dev

test:
  <<: *defaults
  database: allaroundme_test

# production is written by heroku
# look at heroku config to see db link
