defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  host: localhost

development:
  <<: *defaults
  database: allaroundme_dev

test:
  <<: *defaults
  database: allaroundme_test

# production is written by heroku
# look at heroku config to see db link
